### ISSUE TITLE
When I click Login, the page shifts slightly to the left

### ISSUE THREAD

**Issue by aloiselw** [Break-Buddy/Break-Buddy-React#38]
![image](https://github.com/Break-Buddy/Break-Buddy-React/assets/117334364/e613550c-6380-4a4b-906f-873c6671487f)

**Comment by jigolaurito93** [comment]
Finally figured out the problem why it was doing that. Apparently, when you close the modal, the croll bar on the right side appears thats why everything shifts to the left. I installed a node package that removes the scroll bar permanently. Check out the new deployment.
