### ISSUE TITLE
When I click on "sign up" the profile image shows up right away (photo of Tara)

### ISSUE THREAD

**Issue by aloiselw** [Break-Buddy/Break-Buddy-React#51]
![Screenshot 2024-02-20 at 10 10 30 PM](https://github.com/Break-Buddy/Break-Buddy-React/assets/117334364/2948b175-a0ad-4d94-9436-900d5aa359f9)

**Comment by akga20052** [comment]
DO NOT WORRY ABOUT THIS THIS IS GOING TO BE DELETE!!
