### ISSUE TITLE
"Log In" link on Sign up modal does not work

### ISSUE THREAD

**Issue by aloiselw** [Break-Buddy/Break-Buddy-React#52]
![Screenshot 2024-02-20 at 9 42 04 PM](https://github.com/Break-Buddy/Break-Buddy-React/assets/117334364/3669ebc9-919d-4307-922f-025ff7865fd8)

**Comment by Strange-Quark-007** [comment]
While debugging this, I also found that for sign in modal the sign up link was not working

I have fixed that too with this commit and PR as the issues are similar

**Comment by jigolaurito93** [comment]
Done
