### ISSUE TITLE
 add a dimmed/blurred background when the modals popup for signin/account creation to reduce cognitive noise

### ISSUE THREAD

**Issue by aloiselw** [Break-Buddy/Break-Buddy-React#53]
Can we make it 70% dimmed? 
![Screenshot 2024-02-20 at 10 09 07 PM](https://github.com/Break-Buddy/Break-Buddy-React/assets/117334364/d73d932c-e0c0-4e12-82ad-fb1e962cecbe)

**Comment by akga20052** [comment]
yes we can your talking about the background?? would you like it to be a little blurry, blurry and dimmer or only dimmer?
