### ISSUE TITLE
Removed gender (for now) until we test it specifically- it caused some friction during tests

### ISSUE THREAD

**Issue by aloiselw** [Break-Buddy/Break-Buddy-React#64]
![Screenshot 2024-02-26 at 12 24 52 AM](https://github.com/Break-Buddy/Break-Buddy-React/assets/117334364/b15e6dac-1bad-42b8-a6f3-4c66044f2ea2)
![Screenshot 2024-02-26 at 12 41 30 AM](https://github.com/Break-Buddy/Break-Buddy-React/assets/117334364/9cc602fa-344c-4bd9-9c08-619abd1de525)
https://www.figma.com/file/On9lfOsaSut9VtzeIG9i80/Break-Buddy?type=design&node-id=302%3A7897&mode=design&t=pN22lWPtVvYlwgEV-1

**Comment by aloiselw** [comment]
Also made bio text box bigger

**Comment by jigolaurito93** [comment]
Done!
