### ISSUE TITLE
Make Alan O's name and avatar clickable to show his profile

### ISSUE THREAD

**Issue by aloiselw** [Break-Buddy/Break-Buddy-React#68]
To eventually make everyone's avatar and name clickable but for the demo, just 1 to show on the front end
![Screenshot 2024-02-26 at 1 16 20 AM](https://github.com/Break-Buddy/Break-Buddy-React/assets/117334364/08c3b02f-d484-40fc-9226-ef52a04b069c)

**Comment by jigolaurito93** [comment]
I thought we removed the gender for now?

**Comment by jigolaurito93** [comment]
Also, were supposed to remove the "add to private" button right?

**Comment by jigolaurito93** [comment]
Done
