### ISSUE TITLE
Change Post a Break modal 

### ISSUE THREAD

**Issue by aloiselw** [Break-Buddy/Break-Buddy-React#71]
Based on user data, just chat vs. place they will be having their break was confusing. Also just chatting could invite unnecessary attention/make it into a dating app.

keeping it more simple with just 2 (at home/outdoors)

+ added a chat topic to attract people with specific interests
![Screenshot 2024-02-26 at 1 44 26 AM](https://github.com/Break-Buddy/Break-Buddy-React/assets/117334364/05d3daa3-5d07-40aa-98c6-9f0613837535)

**Comment by jigolaurito93** [comment]
Done
