### ISSUE TITLE
Create a Break Modal - 2 changes (change title/ change Private)

### ISSUE THREAD

**Issue by aloiselw** [Break-Buddy/Break-Buddy-React#80]
Not sure if this is done yet, but just in case...
![Screenshot 2024-02-28 at 10 37 34 PM](https://github.com/Break-Buddy/Break-Buddy-React/assets/117334364/c6a9a8a1-20d1-41a9-bbfd-4aa24e8bac76)
![Screenshot 2024-02-28 at 10 37 29 PM](https://github.com/Break-Buddy/Break-Buddy-React/assets/117334364/71953e59-b1c9-4fc4-baf4-d8b0da4a3b58)

**Comment by jigolaurito93** [comment]
DONE
